name = "ob-ai-submit-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[env.production]
name = "ob-ai-submit-proxy"
vars = { RUNPOD_ENDPOINT = "i3qcf6gz8v495h", ENVIRONMENT = "production" }
