name = "ob-ai-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "obaistudio-db"
database_id = "d4c9a2fb-0635-4fcb-bd48-e8faa1a6ae21"

[[r2_buckets]]
binding = "R2_RESULTS"
bucket_name = "ob-ai-results"
