name = "ob-ai-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "obaistudio-db"
database_id = "YOUR_DB_ID"

[[r2_buckets]]
binding = "R2_RESULTS"
bucket_name = "ob-ai-results"

[vars]
RUNPOD_ENDPOINT_ID = "i3qcfgz8v495h"
